version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./dist:/app/dist # This will create the dist folder on the host, which Nginx will then mount

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - frontend:/usr/share/nginx/html # Mount the frontend's build output
      - ./nginx.conf:/etc/nginx/nginx.conf # Mount the custom nginx.conf
    depends_on:
      - backend
      - frontend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - DB_USER=postgres
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
  frontend: # Define the named volume for the frontend build output
