name: CI

on:
  push:
    branches: [ main, ci ]
  pull_request:
    branches: [ main, ci ]

jobs:
  build_application:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - name: Check out code 
      uses: actions/checkout@v4

    - name: Install dependencies
      run: | 
          npm ci
          cd backend
          npm install
          cd tests
          npm ci
          cd ../..

    - name: Run frontend tests - unit and integration
      run: npm test

    - name: Run backend tests
      working-directory: ./backend
      run: npm test
    