name: CI

on:
  push:
    branches: [ main, ci ]
  pull_request:
    branches: [ main, ci ]

jobs:
  build_application:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - name: Check out code 
      uses: actions/checkout@v4

    - name: install dependencies
      run: | 
          npm ci
          cd backend
          npm install
          cd tests
          npm ci
          cd ../..
          echo pwd
